version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    ports:
      - 5004:5000
    environment:
      - APP_SETTINGS=config.DevelopmentConfig
      - DATABASE_URL=postgresql://oob:oob@db:5432/oob
      - FLASK_APP=app.py
      - SECRET_KEY=this-is-a-magic-string-and-i-dont-know-why-i-need-it
      - FLASK_DEBUG=true
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=oob
      - POSTGRES_PASSWORD=oob
      - POSTGRES_DB=oob
    ports:
      - 5436:5432

volumes:
  postgres_data:
