"""post title

Revision ID: 3f4ac706c6e3
Revises: c19ba9dba035
Create Date: 2020-03-22 12:49:13.803054

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3f4ac706c6e3'
down_revision = 'c19ba9dba035'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('title', sa.String(length=256), nullable=True, default=lambda: ''))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'title')
    # ### end Alembic commands ###
