"""add permissions

Revision ID: 55868ce36589
Revises: 12615426d693
Create Date: 2020-03-30 20:33:40.222097

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '55868ce36589'
down_revision = '12615426d693'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    permission_table = op.create_table('permission',
                                       sa.Column('id', sa.Integer(), nullable=False),
                                       sa.Column('name', sa.String(length=128), nullable=False),
                                       sa.PrimaryKeyConstraint('id')
                                       )
    op.create_table('user_permission',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('permission_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('user_id', 'permission_id')
                    )
    op.add_column('post', sa.Column('description', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###

    op.bulk_insert(permission_table, [
        {'name': 'author'}
    ])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'description')
    op.drop_table('user_permission')
    op.drop_table('permission')
    # ### end Alembic commands ###
