"""init

Revision ID: fe5143404ff7
Revises: 
Create Date: 2020-04-08 22:13:09.479962

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
from app import db
from app.models import Permission

revision = 'fe5143404ff7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    permission_table = op.create_table('permission',
                                       sa.Column('id', sa.BigInteger(), nullable=False),
                                       sa.Column('name', sa.String(length=128), nullable=False),
                                       sa.PrimaryKeyConstraint('id')
                                       )
    op.create_table('user',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('username', sa.String(length=64), nullable=True),
                    sa.Column('email', sa.String(length=120), nullable=True),
                    sa.Column('password_hash', sa.String(length=128), nullable=True),
                    sa.Column('first_name', sa.String(length=128), nullable=True),
                    sa.Column('last_name', sa.String(length=128), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('post',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('owner_id', sa.BigInteger(), nullable=False),
                    sa.Column('description', sa.String(length=1024), nullable=True),
                    sa.Column('content', sa.String(length=20000), nullable=True),
                    sa.Column('time_created', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('title', sa.String(length=256), nullable=True),
                    sa.Column('status', postgresql.ENUM('init', 'draft', 'published', 'deleted', name='post_status'),
                              nullable=True),
                    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user_permission',
                    sa.Column('user_id', sa.BigInteger(), nullable=False),
                    sa.Column('permission_id', sa.BigInteger(), nullable=False),
                    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('user_id', 'permission_id')
                    )
    op.create_table('file',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('post_id', sa.BigInteger(), nullable=False),
                    sa.Column('user_id', sa.BigInteger(), nullable=False),
                    sa.Column('url', sa.String(length=512), nullable=False),
                    sa.Column('key', sa.String(length=512), nullable=False),
                    sa.Column('filename', sa.String(length=256), nullable=False),
                    sa.Column('mimetype', sa.String(length=128), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
                    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###

    op.bulk_insert(permission_table, [{
        'name': 'author'
    }])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file')
    op.drop_table('user_permission')
    op.drop_table('post')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('permission')
    # ### end Alembic commands ###
