"""first name, last name

Revision ID: 12615426d693
Revises: 3f4ac706c6e3
Create Date: 2020-03-29 09:14:27.833881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12615426d693'
down_revision = '3f4ac706c6e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###
